// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvQ5PDols3QKi35sqdsQ4PGPyhlmbzmE',
    appId: '1:56749098319:web:d67b56975e7590ec41f13a',
    messagingSenderId: '56749098319',
    projectId: 'earics',
    authDomain: 'earics.firebaseapp.com',
    storageBucket: 'earics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsJ_p9HxfO8L-N4ErOAVJkxgnMd1PMIcw',
    appId: '1:56749098319:android:9a886d7c9bd31bd741f13a',
    messagingSenderId: '56749098319',
    projectId: 'earics',
    storageBucket: 'earics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlJkf7wzpcAVtD7FvJCFukLDYqc9y21Q',
    appId: '1:56749098319:ios:dfa5ad07d44512bb41f13a',
    messagingSenderId: '56749098319',
    projectId: 'earics',
    storageBucket: 'earics.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZlJkf7wzpcAVtD7FvJCFukLDYqc9y21Q',
    appId: '1:56749098319:ios:dfa5ad07d44512bb41f13a',
    messagingSenderId: '56749098319',
    projectId: 'earics',
    storageBucket: 'earics.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvQ5PDols3QKi35sqdsQ4PGPyhlmbzmE',
    appId: '1:56749098319:web:d55c84a6f75259b241f13a',
    messagingSenderId: '56749098319',
    projectId: 'earics',
    authDomain: 'earics.firebaseapp.com',
    storageBucket: 'earics.appspot.com',
  );
}
